name: test-main

on: [push]

jobs:
  test-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install OpenMPI
        run: sudo apt-get update && sudo apt-get install -y libopenmpi-dev openmpi-bin
      - name: build
        run: |
          mkdir build
          cmake -B build -G "Unix Makefiles"
          cmake --build build -- -j4
      - name: exec
        run: ./build/bin/main